export interface SanityImage {
  _type?: 'image'
  asset: {
    _id: string
    url: string
    metadata?: {
      dimensions: { width: number; height: number }
      /** Tiny base64 blur-up placeholder generated by Sanity. */
      lqip?: string
    }
  }
  alt?: string
  caption?: string
}

/** A PDF entry inside an experience gallery. */
export interface GalleryDocument {
  _type: 'galleryDocument'
  title: string
  fileUrl: string
  preview?: SanityImage
  caption?: string
}

export type GalleryEntry = SanityImage | GalleryDocument

export function isGalleryDocument(entry: GalleryEntry): entry is GalleryDocument {
  return entry._type === 'galleryDocument'
}

export interface HeroData {
  headline: string
  headlineItalic?: string
  headlineSuffix?: string
  subheadline: string
  tags?: string[]
}

export interface ProcessStep {
  number: string
  title: string
  description: string
}

export interface AboutData {
  sectionLabel: string
  bio: unknown[]
  processSteps?: ProcessStep[]
  portrait: SanityImage
  signatureImage?: SanityImage
}

export interface ExperienceCategory {
  _id: string
  label: string
  accentLabel: string
  slug: string
  order: number
  hasCompany?: boolean
}

export interface Company {
  _id: string
  name: string
  slug: string
  order?: number
  description?: string
  logo?: SanityImage
  /** Present on the list query; the owning category's _id. */
  categoryId?: string
}

/** The company reference as embedded on an Experience document. */
export interface ExperienceCompany {
  _id: string
  name: string
  slug: string
  order?: number
  logo?: SanityImage
}

export interface Experience {
  _id: string
  title: string
  slug: { current: string }
  studio?: string
  role?: string
  year?: number
  location?: string
  description?: string
  footprint?: string
  materials?: string[]
  category: ExperienceCategory
  company?: ExperienceCompany
  order?: number
  coverImage?: SanityImage
  gallery?: GalleryEntry[]
  externalUrl?: string
  projectPdf?: { asset: { url: string } }
}

export interface SocialLink {
  platform: string
  url: string
}

export interface SiteSettings {
  name?: string
  siteTitle: string
  metaDescription: string
  ogImage?: SanityImage
  socialLinks: SocialLink[]
  email: string
  contactNote: string
  footerTagline: string
  role?: string
  location?: string
  whatsapp?: string
  linkedin?: string
  instagram?: string
  resume?: { asset: { url: string } }
}
